### ISSUE TITLE
Reverse Query Building

### ISSUE THREAD

**Issue by krisgoks** [kindohm/knockout-query-builder#2]
Hello,

Thank you so much for this beautiful tool. Do you have any solution/code to build UI based on query string? For example we have query string ((Goals >= 2 OR Assists >= 1) AND Points <= 5), and UI of groups and conditions is automatically built based on this string?

Thank you

**Comment by kindohm** [comment]
@krisgoks I do not have an example of building the UI from a query string, nor do I have plans to do so. you could potentially serialize an entire JSON object that represents the query into a single string and put that in a single query string param. then load that data when the knockout code starts up. that's just one option.
